### ISSUE TITLE
MinIO chart is deprecated

### ISSUE THREAD

**Issue by sburton-sumo** [OpsMx/spinnaker-helm#12]
The MinIO chart that is in `requirements.yaml` is [deprecated](https://helm.min.io/).  This prevents new Spinnaker chart releases with `minio.enabled` set to `true` from rendering correctly.

**Comment by abhinaybyrisetty** [comment]
Yes, looks like it is replaced by an operator based chart. I'll test it out and update

**Comment by abhinaybyrisetty** [comment]
For now, I have removed the reference to deprecated minio helm repo and added minio chart as dependency chart inside spinnaker chart.

I will thoroughly test new operator based minio chart and update this repo accodingly.
