### ISSUE TITLE
Changes in additionalServiceSettings doesn't apply without a restart to halyard

### ISSUE THREAD

**Issue by liorfranko** [OpsMx/spinnaker-helm#15]
When changing the additionalServiceSettings, the spinnaker-spinnaker-service-settings configmap gets updated, but it doesn't get updated on halyard ~/.hal/default/service-settings/
To workaround it, I need to manually delete the halyard pod and run the install-using-hal Job to apply the changes.

**Comment by abhinaybyrisetty** [comment]
Config map you are talking about is mounted on the init container of halyard, not on the actual container. So, unless halyard is restarted those changes will not be picked up by halyard.

That init container will pre-process these service-settings and place them under ~/.hal/default/service-settings directory...
