### ISSUE TITLE
Question: Skip Validation?

### ISSUE THREAD

**Issue by roee-landesman** [OpsMx/spinnaker-helm#21]
I'm curious why the helm chart recommends the flag `--no-validate` in the saml enablement phase of the halyard setup: https://github.com/OpsMx/spinnaker-helm/blob/main/values_saml.yaml#L70. Is this secure/safe behavior?

**Comment by abhinaybyrisetty** [comment]
I don't see a specific reason why it could have been recommended. Perhaps, this could be removed.
