### ISSUE TITLE
Drop obsolete `artifacts` feature flag

### ISSUE THREAD

**Issue by hisener** [OpsMx/spinnaker-helm#5]
IIUC Spinnaker artifacts are enabled by default in Spinnaker 1.20+. Since the chart uses `1.22.2`, we should be able to drop it from `spinnakerFeatureFlags`.
https://github.com/OpsMx/spinnaker-helm/blob/0eb54590391fa219cb0dc7e32bbbf73b26d9c809/values.yaml#L242-L243

Relevant logs:
```
Validation in default.features:
- WARNING Field Features.artifacts not supported for Spinnaker
  version 1.24.3: Artifacts are now enabled by default.
? You no longer need this.
```
(I did upgrade the spinnakerVersion but it's the same for the default version.)

**Comment by abhinayopsmx** [comment]
@hisener I will create a PR to fix this issue.
